
public class Test
{
    public static void main(String args[])
    {
        //String Packet = "Update 192.168.1.100 0 100 CelineDion 100000 Slipknot 100000";
        String message = "update ";
        String Packet = "HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_HELLO_WORLD_IDRIS_SUCKS_";
        int LENGTH = (Packet.getBytes()).length;
        int numPackets;
        byte[] header = new byte[7];
        header = Packet.getBytes();


        byte[] sendData = new byte[LENGTH];
        sendData = Packet.getBytes();
        
        
        if((sendData.length%121)!=0){numPackets = ((LENGTH / 121) +1);}
        else{numPackets = (LENGTH / 121);}
        System.out.println("numPackets " + numPackets);

        for( int i=0; i<numPackets;i++){
            int j=0;
            byte[] sendPkt = new byte[128];
            while(((i*121) + j)< LENGTH && j<121){
                System.out.println(j);
                sendPkt[j] = sendData[(i*121) + j];
                j++;
            }
            
            String str = new String(sendPkt);
            System.out.println(str);
        }
    }
}
